version: "3.9"
services:
  crisis-frontend:
    image: crisis-frontend:sony
    container_name: crisis-frontend-container-sony
    ports:
      - "3001:80"
    networks:
      crisisnetwork:
        ipv4_address: 172.20.3.8
    env_file:
      - .env
networks:
  crisisnetwork:
    name: crisisnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
