version: "3.9"
services:
  crisis-backend:
    image: crisis-backend:sony
    container_name: crisis-backend-container-sony
    ports:
      - "3601:3601"
    # Connect to network crisisnetwork
    networks:
      crisisnetwork:
        ipv4_address: 172.20.1.3

networks:
  crisisnetwork:
    name: crisisnetwork
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
